"""Phase 1 report builder — assembles all outputs into a comprehensive HTML report."""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd

from src.utils.paths import reports_dir, figures_dir, tables_dir
from src.utils.serialization import save_json
from src.utils.logging import get_logger

logger = get_logger(__name__)

REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Phase 1 Research Report — Hett</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; margin: 40px; color: #222; background: #fafafa; }}
  h1 {{ color: #1a3a5c; border-bottom: 2px solid #1a3a5c; padding-bottom: 8px; }}
  h2 {{ color: #2c5f8a; margin-top: 32px; }}
  h3 {{ color: #3a7abf; }}
  table {{ border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 13px; }}
  th {{ background: #1a3a5c; color: white; padding: 8px 12px; text-align: left; }}
  td {{ padding: 6px 12px; border-bottom: 1px solid #ddd; }}
  tr:nth-child(even) {{ background: #f0f4f8; }}
  .warning {{ background: #fff3cd; padding: 12px; border-left: 4px solid #ffc107; margin: 8px 0; }}
  .info {{ background: #d1ecf1; padding: 12px; border-left: 4px solid #17a2b8; margin: 8px 0; }}
  .pass {{ background: #d4edda; padding: 12px; border-left: 4px solid #28a745; margin: 8px 0; }}
  .fail {{ background: #f8d7da; padding: 12px; border-left: 4px solid #dc3545; margin: 8px 0; }}
  img {{ max-width: 100%; margin: 16px 0; border: 1px solid #ddd; border-radius: 4px; }}
  pre {{ background: #f4f4f4; padding: 12px; border-radius: 4px; font-size: 12px; overflow-x: auto; }}
  .section {{ background: white; padding: 20px; margin: 16px 0; border-radius: 6px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
</style>
</head>
<body>
<h1>Phase 1 Research Report: NIFTY 50 Edge Discovery</h1>
<p><strong>Generated:</strong> {generated_at}</p>
<p><strong>Data:</strong> {data_coverage}</p>
<p><strong>WARNING:</strong> ^NSEI is an index — it cannot be traded directly.
All costs are indicative assumptions for sensitivity testing only. Past backtested performance
does not represent achievable future returns.</p>

{sections}

<hr>
<p><em>Report generated by Hett Phase 1 Research System. All findings are exploratory and require
further validation before any real-money application.</em></p>
</body>
</html>
"""


class ReportBuilder:
    def __init__(self, base: Optional[Path] = None):
        self.base = base or reports_dir()
        self.fig_dir = figures_dir()
        self.tbl_dir = tables_dir()
        self.sections: List[str] = []

    def add_section(self, title: str, content: str) -> None:
        self.sections.append(
            f'<div class="section"><h2>{title}</h2>{content}</div>'
        )

    def add_data_quality(self, report: dict) -> None:
        errors = report.get("confirmed_errors", [])
        warnings = report.get("validation_warnings", [])
        notes = report.get("notes", [])

        html = f"""
        <p><strong>Symbol:</strong> {report.get('symbol')} |
           <strong>Source:</strong> {report.get('source')} |
           <strong>Downloaded:</strong> {report.get('downloaded_at','N/A')[:19]}</p>
        <p><strong>Date range:</strong> {report.get('first_date')} → {report.get('last_date')}</p>
        <p><strong>Rows:</strong> {report.get('total_rows')} |
           <strong>Duplicates:</strong> {report.get('duplicate_dates')} |
           <strong>Suspected gaps:</strong> {len(report.get('suspected_gaps',[]))} |
           <strong>Extreme returns:</strong> {len(report.get('extreme_returns',[]))}</p>
        """
        if errors:
            html += "<div class='fail'><strong>Confirmed Errors:</strong><ul>" + "".join(f"<li>{e}</li>" for e in errors) + "</ul></div>"
        if warnings:
            html += "<div class='warning'><strong>Warnings:</strong><ul>" + "".join(f"<li>{w}</li>" for w in warnings) + "</ul></div>"
        for n in notes:
            html += f"<div class='info'>{n}</div>"

        self.add_section("Data Quality", html)

    def add_metrics_table(self, metrics_dict: Dict[str, dict], title: str = "Performance Metrics") -> None:
        from src.reports.tables import metrics_table
        df = metrics_table(metrics_dict)
        self.add_section(title, df.to_html(classes="", border=0))

    def add_image(self, path: Optional[Path], caption: str = "") -> str:
        if path is None or not Path(path).exists():
            return f"<p><em>Chart not available: {caption}</em></p>"
        rel = Path(path).name
        return f'<figure><img src="../figures/{rel}" alt="{caption}"><figcaption>{caption}</figcaption></figure>'

    def add_candidate_results(self, results: List[dict]) -> None:
        if not results:
            html = "<p>No candidate experiments completed.</p>"
        else:
            accepted = [r for r in results if r.get("status") == "accepted"]
            rejected = [r for r in results if r.get("status") == "rejected"]
            html = f"<p><strong>Total experiments:</strong> {len(results)} | "
            html += f"<strong>Accepted (val):</strong> {len(accepted)} | "
            html += f"<strong>Rejected:</strong> {len(rejected)}</p>"

            if accepted:
                html += "<h3>Accepted Candidates</h3><table><tr><th>ID</th><th>Description</th><th>Val EV</th><th>Val Hit Rate</th><th>Val N</th></tr>"
                for r in accepted:
                    sv = r.get("stats_val", {})
                    html += f"<tr><td>{r['experiment_id']}</td><td>{r['description']}</td>"
                    html += f"<td>{sv.get('mean', 0)*100:.3f}%</td>"
                    html += f"<td>{sv.get('hit_rate', 0):.1%}</td>"
                    html += f"<td>{sv.get('n', 0)}</td></tr>"
                html += "</table>"

            if rejected:
                html += "<h3>Rejected Candidates</h3><table><tr><th>ID</th><th>Reason</th></tr>"
                for r in rejected:
                    html += f"<tr><td>{r['experiment_id']}</td><td>{r.get('rejection_reason','')}</td></tr>"
                html += "</table>"

        self.add_section("Candidate Edge Results", html)

    def add_go_no_go(self, decision: str, rationale: str) -> None:
        cls = "pass" if decision == "GO" else "fail"
        html = f"<div class='{cls}'><h3>Phase 2 Recommendation: {decision}</h3><p>{rationale}</p></div>"
        self.add_section("Phase 2 Recommendation", html)

    def add_limitations(self) -> None:
        html = """
        <ul>
        <li><strong>Index proxy:</strong> ^NSEI cannot be traded directly. Backtest costs are hypothetical.</li>
        <li><strong>Survivorship:</strong> NIFTY 50 composition changes over time. Index-level analysis avoids stock selection but is subject to index reconstitution effects.</li>
        <li><strong>Tax treatment:</strong> STCG/LTCG and other taxes are not modelled.</li>
        <li><strong>Liquidity:</strong> No intraday liquidity constraints are modelled.</li>
        <li><strong>Gap risk:</strong> Overnight gaps can cause material slippage beyond modelled assumptions.</li>
        <li><strong>Multiple testing:</strong> Despite FDR correction, some results may be spurious. OOS confirmation is required.</li>
        <li><strong>Regime stability:</strong> Future regimes may differ from historical distributions used for threshold fitting.</li>
        <li><strong>No RL:</strong> Reinforcement learning is intentionally excluded from Phase 1. RL would only be considered after a robust OOS edge is confirmed.</li>
        </ul>
        """
        self.add_section("Known Limitations", html)

    def build(
        self,
        data_coverage: str = "",
        generated_at: Optional[str] = None,
    ) -> Path:
        self.base.mkdir(parents=True, exist_ok=True)
        generated_at = generated_at or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        html = REPORT_TEMPLATE.format(
            generated_at=generated_at,
            data_coverage=data_coverage,
            sections="\n".join(self.sections),
        )
        report_path = self.base / "phase1_report.html"
        with open(report_path, "w") as f:
            f.write(html)
        logger.info(f"Report written to {report_path}")
        return report_path
